# Site settings
title: recology
email: myrmecocystus@gmail.com
description: code and such
permalink:    /:year/:month/:title/
baseurl: ""
url: "https://recology.info"
mastodon_username: "@sckottie@fosstodon.org"
github_username:  sckott
paginate: 5

plugins: [jekyll-paginate, kramdown, jekyll-algolia]

markdown: kramdown

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
