# Site settings
title: recology
email: myrmecocystus@gmail.com
description: code and such
permalink:    /:year/:month/:title/
baseurl: ""
url: "https://recology.info"
mastodon_username: "@sckottie@fosstodon.org"
github_username:  sckott
paginate: 5

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
# kramdown:
#   syntax_highlighter: rouge
