baseURL = 'https://recology.info/'
languageCode = 'en-us'
title = 'Recology'
theme = 'PaperMod'
rssLimit = 10
ignoreLogs = ['warning-goldmark-raw-html']

[markup.goldmark.renderer]
unsafe = true

[params.meta]
favicon = false

[params]
ShowCodeCopyButtons = true
ShowReadingTime = true
defaultTheme = "auto"
showFullTextInRss = true
mainSections = ["posts"]

features = ["archive", "search"]

[menu]
[[menu.main]]
name = 'Home'
url = '/'
weight = 10
[[menu.main]]
name = 'Archive'
url = '/archives'
weight = 20
[[menu.main]]
name = 'About'
url = '/about'
weight = 30
[[menu.main]]
name = 'Links'
url = '/links'
weight = 40
[[menu.main]]
name = 'Search'
url = '/search'
weight = 50
[[menu.main]]
name = 'RSS'
url = '/posts/index.xml'
weight = 60

[outputs]
home = ['HTML', 'RSS', 'JSON']
section = ['HTML', 'RSS']

[permalinks]
[permalinks.page]
posts = '/:year/:month/:filename/'
links = '/:section/:year/:month/:filename/'
