baseURL = 'https://recology.info/'
languageCode = 'en-us'
title = 'Recology'
theme = 'PaperMod'
rssLimit = 10

[params.meta]
  favicon = false

[params]
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  defaultTheme = "auto"
  showFullTextInRss = true

features = [
  "archive",
  "search"
]

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 20
[[menu.main]]
  name = 'Archive'
  url = '/archives'
  weight = 30
[[menu.main]]
  name = 'Search'
  url = '/search'
  weight = 40
[[menu.main]]
  name = 'RSS'
  url = '/index.xml'
  weight = 50

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[permalinks]
  [permalinks.page]
    posts = '/:year/:month/:filename/'
