[context.production]
publish = "public"
command = "hugo --config=hugo.toml --baseURL=https://recology.info/"

[context.deploy-preview]
publish = "public"
command = "hugo --config=hugo.toml --baseURL=$DEPLOY_PRIME_URL"
