<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-us">

  <head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
  <link href="http://gmpg.org/xfn/11" rel="profile">

  <title>
    
    Recology, R ecology
  </title>

  <!-- CSS -->
  <link rel="stylesheet" href="/public/css/hyde.css">
  <link rel="stylesheet" href="/public/css/syntax.css">
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400italic,400,600,700|Abril+Fatface">


  <!-- Icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/public/favicon.ico">
  <link rel="shortcut icon" href="/public/favicon.ico">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.css" rel="stylesheet">

  <!-- RSS -->
  <link rel="alternate" type="application/rss+xml" title="RSS" href="/atom.xml">
</head>


  <body class="theme-base-0f layout-reverse">

    <header class="masthead">
      <div class="masthead-inner">
        <h1>Recology</h1>
        <!-- <h1> <a href="http://recology.info/">Recology</a></h1> -->
        <p class="lead">R/etc.</p>

        <div class="colophon">
          <ul class="colophon-links">
            <li>
              <a href="/"><i class="fa fa-home fa-lg"></i></a>&nbsp;
              <a href="/about"><i class="fa fa-info-circle fa-lg"></i></a>&nbsp;
              <a href="/archives"><i class="fa fa-archive fa-lg"></i></a>&nbsp;
              <a href="/rresources"><i class="fa fa-book fa-lg"></i></a>&nbsp;
              <a href="http://rforcats.net/" rel><i class="fa fa-graduation-cap fa-lg"></i></a>&nbsp;
              <a href="http://feeds.feedburner.com/github/wpna"><i class="fa fa-rss fa-lg"></i></a>&nbsp;
              <a href="https://twitter.com/recology_"><i class="fa fa-twitter fa-lg"></i></a>&nbsp;
              <a href="/fork"><i class="fa fa-spinner fa-lg"></i></a>
            </li>
          </ul>
          <!-- <small><a href="https://github.com/mdo/hyde">Hyde</a> from <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.</small> -->
        </div>
      </div>
    </header>

    <div class="content container">
      <div class="posts">
  <a style="float:right;" href="/archives"><i class="fa fa-archive fa-lg"></i></a>
  
  <div class="post">
    <h1>
      <a href="/2014/06/analogsea-v01/">
        analogsea - v0.1 notes
      </a>
    </h1>

    <span class="post-date">18 Jun 2014</span>

    <p>My <a href="http://recology.info/2014/05/analogsea/">last blog </a> post introduced the R package I'm working on <code>analogsea</code>, an R client for the Digital Ocean API.</p>

<p>Things have changed a bit, including fillig out more functions for all API endpoints, and incorparting feedback from Hadley and Karthik. The package is as <code>v0.1</code> now, so I thought I'd say a few things about how it works.</p>

<p>Note that Digital Ocean's v2 API is in beta stage now, so the current version of <code>analogsea</code> at <code>v0.1</code> works with their v1 API. The <a href="https://github.com/sckott/analogsea/tree/v2">v2 branch of analogsea</a> is being developed for their v2 API.</p>

<p>If you sign up for an account with Digital Ocean use this referral link: <a href="https://www.digitalocean.com/?refcode=0740f5169634">https://www.digitalocean.com/?refcode=0740f5169634</a> so I can earn some credits. thx :)</p>

<p>First, installation</p>

<p>Note: I did try to submit to CRAN, but Ripley complained about the package name so I'd rather not waste my time esp since people using this likely will already know about <code>install_github()</code>.</p>

<pre><code class="r">devtools::install_github("sckott/analogsea")
</code></pre>

<p>Load the library</p>

<pre><code class="r">library("analogsea")
</code></pre>

<pre><code>## Loading required package: magrittr
</code></pre>

<p>Authenticate has changed a bit. Whereas auth details were stored as environment variables before, I'm just using R's options. <code>do_auth()</code> will ask for your Digital Ocean details. You can enter them each R session, or store them in your <code>.Rprofile</code> file. After successful authentication, each function simply looks for your auth details with <code>getOption()</code>.  You don't have to use this function first, though if you don't your first call to another function will ask for auth details.</p>

<pre><code class="r">do_auth()
</code></pre>

<p><code>sizes</code>, <code>images</code>, and <code>keys</code> functions have changed a bit, by default outputting a <code>data.frame</code> now.</p>

<p>List available regions</p>

<pre><code class="r">regions()
</code></pre>

<pre><code>##   id            name slug
## 1  3 San Francisco 1 sfo1
## 2  4      New York 2 nyc2
## 3  5     Amsterdam 2 ams2
## 4  6     Singapore 1 sgp1
</code></pre>

<p>List available sizes</p>

<pre><code class="r">sizes()
</code></pre>

<pre><code>##   id  name  slug memory cpu disk cost_per_hour cost_per_month
## 1 66 512MB 512mb    512   1   20       0.00744            5.0
## 2 63   1GB   1gb   1024   1   30       0.01488           10.0
## 3 62   2GB   2gb   2048   2   40       0.02976           20.0
## 4 64   4GB   4gb   4096   2   60       0.05952           40.0
## 5 65   8GB   8gb   8192   4   80       0.11905           80.0
## 6 61  16GB  16gb  16384   8  160       0.23810          160.0
## 7 60  32GB  32gb  32768  12  320       0.47619          320.0
## 8 70  48GB  48gb  49152  16  480       0.71429          480.0
## 9 69  64GB  64gb  65536  20  640       0.95238          640.0
</code></pre>

<p>List available images</p>

<pre><code class="r">head(images())
</code></pre>

<pre><code>##        id                  name             slug distribution public sfo1
## 1 3209452 rstudioserverssh_snap             &lt;NA&gt;       Ubuntu  FALSE    1
## 2    1601        CentOS 5.8 x64   centos-5-8-x64       CentOS   TRUE    1
## 3    1602        CentOS 5.8 x32   centos-5-8-x32       CentOS   TRUE    1
## 4   12573        Debian 6.0 x64   debian-6-0-x64       Debian   TRUE    1
## 5   12575        Debian 6.0 x32   debian-6-0-x32       Debian   TRUE    1
## 6   14097      Ubuntu 10.04 x64 ubuntu-10-04-x64       Ubuntu   TRUE    1
##   nyc1 ams1 nyc2 ams2 sgp1
## 1   NA   NA   NA   NA   NA
## 2    1    1    1    1    1
## 3    1    1    1    1    1
## 4    1    1    1    1    1
## 5    1    1    1    1    1
## 6    1    1    1    1    1
</code></pre>

<p>List ssh keys</p>

<pre><code class="r">keys()
</code></pre>

<pre><code>## $ssh_keys
## $ssh_keys[[1]]
## $ssh_keys[[1]]$id
## [1] 89103
##
## $ssh_keys[[1]]$name
## [1] "Scott Chamberlain"
</code></pre>

<p>One change that's of interest is that most of the various <code>droplets_*()</code> functions take in the outputs of other <code>droplets_*()</code> functions. This means that we can pipe outputs of one <code>droplets_*()</code> function to another, including non-<code>droplet_*</code> functions (see examples).</p>

<p>Let's create a droplet:</p>

<pre><code class="r">(res &lt;- droplets_new(name="foo", size_slug = '512mb', image_slug = 'ubuntu-14-04-x64', region_slug = 'sfo1', ssh_key_ids = 89103))
</code></pre>

<pre><code class="r">$droplet
$droplet$id
[1] 1880805

$droplet$name
[1] "foo"

$droplet$image_id
[1] 3240036

$droplet$size_id
[1] 66

$droplet$event_id
[1] 26711810
</code></pre>

<p>List my droplets</p>

<p>This function used to be <code>do_droplets_get()</code></p>

<pre><code class="r">droplets()
</code></pre>

<pre><code>## $droplet_ids
## [1] 1880805
##
## $droplets
## $droplets[[1]]
## $droplets[[1]]$id
## [1] 1880805
##
## $droplets[[1]]$name
## [1] "foo"
##
## $droplets[[1]]$image_id
## [1] 3240036
##
## $droplets[[1]]$size_id
## [1] 66
##
## $droplets[[1]]$region_id
## [1] 3
##
## $droplets[[1]]$backups_active
## [1] FALSE
##
## $droplets[[1]]$ip_address
## [1] "162.243.152.56"
##
## $droplets[[1]]$private_ip_address
## NULL
##
## $droplets[[1]]$locked
## [1] FALSE
##
## $droplets[[1]]$status
## [1] "active"
##
## $droplets[[1]]$created_at
## [1] "2014-06-18T14:15:35Z"
##
##
##
## $event_id
## NULL
</code></pre>

<p>As mentioned above we can now pipe output of <code>droplet*()</code> functions to other <code>droplet*()</code> functions.</p>

<p>Here, pipe output of lising droplets <code>droplets()</code> to the <code>events()</code> function</p>

<pre><code class="r">droplets() %&gt;% events()
</code></pre>

<pre><code>## Error: No event id found
</code></pre>

<p>In this case there were no event ids to get event data on.</p>

<p>Here, we'll get details for the droplet we just created, then pipe that to <code>droplets_power_off()</code></p>

<pre><code class="r">droplets(1880805) %&gt;% droplets_power_off
</code></pre>

<pre><code>## $droplet_ids
## [1] 1880805
##
## $droplets
## $droplets$droplet_ids
## [1] 1880805
##
## $droplets$droplets
## $droplets$droplets$id
## [1] 1880805
##
## $droplets$droplets$name
## [1] "foo"
##
## $droplets$droplets$image_id
## [1] 3240036
##
## $droplets$droplets$size_id
## [1] 66
##
## $droplets$droplets$region_id
## [1] 3
##
## $droplets$droplets$backups_active
## [1] FALSE
##
## $droplets$droplets$ip_address
## [1] "162.243.152.56"
##
## $droplets$droplets$private_ip_address
## NULL
##
## $droplets$droplets$locked
## [1] FALSE
##
## $droplets$droplets$status
## [1] "active"
##
## $droplets$droplets$created_at
## [1] "2014-06-18T14:15:35Z"
##
## $droplets$droplets$backups
## list()
##
## $droplets$droplets$snapshots
## list()
##
##
## $droplets$event_id
## NULL
##
##
## $event_id
## [1] 26714109
</code></pre>

<p>Then pipe it again to <code>droplets_power_on()</code></p>

<pre><code class="r">droplets(1880805) %&gt;%
  droplets_power_on
</code></pre>

<pre><code>## $droplet_ids
## [1] 1880805
##
## $droplets
## $droplets$droplet_ids
## [1] 1880805
##
## $droplets$droplets
## $droplets$droplets$id
## [1] 1880805
##
## $droplets$droplets$name
## [1] "foo"
##
## $droplets$droplets$image_id
## [1] 3240036
##
## $droplets$droplets$size_id
## [1] 66
##
## $droplets$droplets$region_id
## [1] 3
##
## $droplets$droplets$backups_active
## [1] FALSE
##
## $droplets$droplets$ip_address
## [1] "162.243.152.56"
##
## $droplets$droplets$private_ip_address
## NULL
##
## $droplets$droplets$locked
## [1] FALSE
##
## $droplets$droplets$status
## [1] "off"
##
## $droplets$droplets$created_at
## [1] "2014-06-18T14:15:35Z"
##
## $droplets$droplets$backups
## list()
##
## $droplets$droplets$snapshots
## list()
##
##
## $droplets$event_id
## NULL
##
##
## $event_id
## [1] 26714152
</code></pre>

<pre><code class="r">Sys.sleep(6)
droplets(1880805)$droplets$status
</code></pre>

<pre><code>## [1] "off"
</code></pre>

<p>Why not use more pipes?</p>

<pre><code class="r">droplets(1880805) %&gt;%
  droplets_power_off %&gt;%
  droplets_power_on %&gt;%
  events
</code></pre>

<hr />

<p>Last time I talked about installing R, RStudio, etc. on a droplet. I'm still working out bugs in that stuff, but do test out so it can get better faster. See <code>do_install()</code>.</p>

  </div>
  
  <div class="post">
    <h1>
      <a href="/2014/05/analogsea/">
        analogsea - an R client for the Digital Ocean API
      </a>
    </h1>

    <span class="post-date">28 May 2014</span>

    <p>I think this package name is my best yet. Maybe it doesn't make sense though? At least it did at the time...</p>

<p>Anyway, the main motivation for this package was to be able to automate spinning up Linux boxes to do cloud R/RStudio work. Of course if you are a command line native this is all easy for you, but if you are afraid of the command line and/or just don't want to deal with it, this tool will hopefully help.</p>

<p>Most of the functions in this package wrap the Digital Ocean API. So you can do things like create a new <em>droplet</em>, get information on your droplets, <em>destroy</em> droplets, get information on available images, make snapshots, etc. Basically everything you can do from their website you can do here. Note that all functions are prefixed with <code>do_</code> (for Digital Ocean).</p>

<p>The droplet creation part is what we can leverage to spin up a cloud machine to then install R on, and optionally RStudio server, and even RStudio Shiny server. This allows you to stay within R entirely, not having to go to <code>ssh</code> into the Linux machine itself or go to the Digital Ocean website (after initial setup of course).</p>

<p>If you try this, I recommend using this on R on the command line as you can more easily kill the R session if something goes wrong, and quickly open a new tab/window to <code>ssh</code> into the Linux machine if you want.</p>

<p>First, installation</p>

<pre><code class="r">devtools::install_github("sckott/analogsea")
</code></pre>

<p>Load the library</p>

<pre><code class="r">library("analogsea")
</code></pre>

<p>Firt, authenticate. This will ask for your Digital Ocean details. You can enter them each R session, or store them in your <code>.Renviron</code> file. After successful authentication, each function simply looks for your auth details with <code>Sys.getenv()</code>.</p>

<pre><code class="r">do_auth()
</code></pre>

<p>List available regions</p>

<pre><code class="r">sapply(do_regions()$regions, "[[", "name")
</code></pre>

<pre><code>## [1] "San Francisco 1" "New York 2"      "Amsterdam 2"     "Singapore 1"
</code></pre>

<p>List available images</p>

<pre><code class="r">sapply(do_images()$images, "[[", "name")
</code></pre>

<pre><code>##  [1] "rstudioserverssh_snap"                          
##  [2] "CentOS 5.8 x64"                                 
##  [3] "CentOS 5.8 x32"                                 
##  [4] "Debian 6.0 x64"                                 
##  [5] "Debian 6.0 x32"                                 
##  [6] "Ubuntu 10.04 x64"                               
##  [7] "Ubuntu 10.04 x32"                               
##  [8] "Arch Linux 2013.05 x64"                         
##  [9] "Arch Linux 2013.05 x32"                         
## [10] "CentOS 6.4 x32"                                 
## [11] "CentOS 6.4 x64"                                 
## [12] "Ubuntu 12.04.4 x32"                             
## [13] "Ubuntu 12.04.4 x64"                             
## [14] "Ubuntu 13.10 x32"                               
## [15] "Ubuntu 13.10 x64"                               
## [16] "Fedora 19 x32"                                  
## [17] "Fedora 19 x64"                                  
## [18] "MEAN on Ubuntu 12.04.4"                         
## [19] "Ghost 0.4.2 on Ubuntu 12.04"                    
## [20] "Wordpress on Ubuntu 13.10"                      
## [21] "Ruby on Rails on Ubuntu 12.10 (Nginx + Unicorn)"
## [22] "Redmine on Ubuntu 12.04"                        
## [23] "Ubuntu 14.04 x32"                               
## [24] "Ubuntu 14.04 x64"                               
## [25] "Fedora 20 x32"                                  
## [26] "Fedora 20 x64"                                  
## [27] "Dokku v0.2.3 on Ubuntu 14.04"                   
## [28] "Debian 7.0 x64"                                 
## [29] "Debian 7.0 x32"                                 
## [30] "CentOS 6.5 x64"                                 
## [31] "CentOS 6.5 x32"                                 
## [32] "Docker 0.11.1 on Ubuntu 13.10 x64"              
## [33] "Django on Ubuntu 14.04"                         
## [34] "LAMP on Ubuntu 14.04"                           
## [35] "node-v0.10.28 on Ubuntu 14.04"                  
## [36] "GitLab 6.9.0 CE"
</code></pre>

<p>List available sizes</p>

<pre><code class="r">do.call(rbind, do_sizes()$sizes)
</code></pre>

<pre><code>##       id name    slug    memory cpu disk cost_per_hour cost_per_month
##  [1,] 66 "512MB" "512mb" 512    1   20   0.00744       "5.0"         
##  [2,] 63 "1GB"   "1gb"   1024   1   30   0.01488       "10.0"        
##  [3,] 62 "2GB"   "2gb"   2048   2   40   0.02976       "20.0"        
##  [4,] 64 "4GB"   "4gb"   4096   2   60   0.05952       "40.0"        
##  [5,] 65 "8GB"   "8gb"   8192   4   80   0.1191        "80.0"        
##  [6,] 61 "16GB"  "16gb"  16384  8   160  0.2381        "160.0"       
##  [7,] 60 "32GB"  "32gb"  32768  12  320  0.4762        "320.0"       
##  [8,] 70 "48GB"  "48gb"  49152  16  480  0.7143        "480.0"       
##  [9,] 69 "64GB"  "64gb"  65536  20  640  0.9524        "640.0"
</code></pre>

<p>Let's create a droplet:</p>

<pre><code class="r">(res &lt;- do_droplets_new(name="foo", size_slug = '512mb', image_slug = 'ubuntu-14-04-x64', region_slug = 'sfo1', ssh_key_ids = 89103))
</code></pre>

<pre><code class="r">$status
[1] "OK"

$droplet
$droplet$id
[1] 1733336

$droplet$name
[1] "foo"

$droplet$image_id
[1] 3240036

$droplet$size_id
[1] 66

$droplet$event_id
[1] 25278892


attr(,"class")
[1] "dodroplet"
</code></pre>

<p>List my droplets</p>

<pre><code class="r">do_droplets_get()
</code></pre>

<pre><code>## $status
## [1] "OK"
## 
## $droplets
## $droplets[[1]]
## $droplets[[1]]$id
## [1] 1733336
## 
## $droplets[[1]]$name
## [1] "foo"
## 
## $droplets[[1]]$image_id
## [1] 3240036
## 
## $droplets[[1]]$size_id
## [1] 66
## 
## $droplets[[1]]$region_id
## [1] 3
## 
## $droplets[[1]]$backups_active
## [1] FALSE
## 
## $droplets[[1]]$ip_address
## [1] "107.170.211.252"
## 
## $droplets[[1]]$private_ip_address
## NULL
## 
## $droplets[[1]]$locked
## [1] FALSE
## 
## $droplets[[1]]$status
## [1] "active"
## 
## $droplets[[1]]$created_at
## [1] "2014-05-28T05:59:22Z"
</code></pre>

<p>Cool, we have a new Linux box with 512 mb RAM, running Ubuntu 14.04 in the SF region. Notice that I'm using my SSH key here. If you don't use your SSH key, Digital Ocean will email you a password, which you then use. We just have to wait a bit (sometimes 20 seconds, sometimes a few minutes) for it to spin up.</p>

<p>Now we can install stuff. Here, I'll install R, and RStudio Server. This step prints out the progress as you would see if you did <code>ssh</code> into the box itself outside of R. The RStudio Server instance will pop up in your default browser when this operation is done.</p>

<pre><code class="r">do_install(res$droplet$id, what='rstudio', usr='hey', pwd='there')
</code></pre>

<p><img src="/public/img/2014-05-28-analogsea/rstudioinstance.png" width="100%"></p>

<p>You can install some things like the <code>libcurl</code> and <code>libxml</code> libraries too with the <code>deps</code> parameter.</p>

<p>When you're done, you can destroy your droplet from R too</p>

<pre><code class="r">do_droplets_destroy(res$droplet$id)
</code></pre>

<pre><code>## $status
## [1] "OK"
## 
## $event_id
## [1] 25279124
</code></pre>

<p>Let me know if you have any thoughts :)</p>

  </div>
  
  <div class="post">
    <h1>
      <a href="/2014/05/logplotreboot/">
        Logistic plot reboot
      </a>
    </h1>

    <span class="post-date">22 May 2014</span>

    <p>Someone asked about plotting something like this today</p>

<p>I <a href="http://recology.info/2012/01/logistic-regression-barplot-fig/">wrote a few functions previously</a> to do something like this. However, since then <code>ggplot2</code> has changed, and one of the functions no longer works.</p>

<p>Hence, I fixed <code>opts()</code> to <code>theme()</code>, <code>theme_blank()</code> to <code>element_blank()</code>, and <code>panel.background = element_blank()</code> to <code>plot.background = element_blank()</code> to get the histograms to show up with the line plot and not cover it.</p>

<p>The new functions:</p>

<pre><code class="r">loghistplot  &lt;- function(data) {
  names(data) &lt;- c('x','y') # rename columns

  # get min and max axis values
  min_x &lt;- min(data$x)
  max_x &lt;- max(data$x)
  min_y &lt;- min(data$y)
  max_y &lt;- max(data$y)

  # get bin numbers
  bin_no &lt;- max(hist(data$x, plot = FALSE)$counts) + 5

  # create plots
  a &lt;- ggplot(data, aes(x = x, y = y)) +
    theme_bw(base_size=16) +
    geom_smooth(method = "glm", family = "binomial", se = TRUE,
                colour='black', size=1.5, alpha = 0.3) +
    scale_x_continuous(limits=c(min_x,max_x)) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor=element_blank(),
          panel.background = element_blank(),
          plot.background = element_blank()) +
    labs(y = "Probability\n", x = "\nYour X Variable")

  theme_loghist &lt;- list(
    theme(panel.grid.major = element_blank(),
          panel.grid.minor=element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_blank(),
          axis.ticks = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          plot.background = element_blank())
  )

  b &lt;-
  ggplot(data[data$y == unique(data$y)[1], ], aes(x = x)) +
    theme_bw(base_size=16) +
    geom_histogram(fill = "grey") +
    scale_y_continuous(limits=c(0,bin_no)) +
    scale_x_continuous(limits=c(min_x,max_x)) +
    theme_loghist +
    labs(y='\n', x='\n')

  c &lt;- ggplot(data[data$y == unique(data$y)[2], ], aes(x = x)) +
    theme_bw(base_size=16) +
    geom_histogram(fill = "grey") +
    scale_y_continuous(trans='reverse', limits=c(bin_no,0)) +
    scale_x_continuous(limits=c(min_x,max_x)) +
    theme_loghist +
    labs(y='\n', x='\n')

  grid.newpage()
  pushViewport(viewport(layout = grid.layout(1,1)))

  vpa_ &lt;- viewport(width = 1, height = 1, x = 0.5, y = 0.5)
  vpb_ &lt;- viewport(width = 1, height = 1, x = 0.5, y = 0.5)
  vpc_ &lt;- viewport(width = 1, height = 1, x = 0.5, y = 0.5)

  print(b, vp = vpb_)
  print(c, vp = vpc_)
  print(a, vp = vpa_)
}
</code></pre>

<pre><code class="r">logpointplot  &lt;- function(data) {
  names(data) &lt;- c('x','y') # rename columns

  # get min and max axis values
  min_x &lt;- min(data$x)
  max_x &lt;- max(data$x)
  min_y &lt;- min(data$y)
  max_y &lt;- max(data$y)

  # create plots
  ggplot(data, aes(x = x, y = y)) +
    theme_bw(base_size=16) +
    geom_point(size = 3, alpha = 0.5, position = position_jitter(w=0, h=0.02)) +
    geom_smooth(method = "glm", family = "binomial", se = TRUE,
                colour='black', size=1.5, alpha = 0.3) +
    scale_x_continuous(limits=c(min_x,max_x)) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor=element_blank(),
          panel.background = element_blank()) +
    labs(y = "Probability\n", x = "\nYour X Variable")

}
</code></pre>

<p>Install <code>ggplot2</code> and <code>gridExtra</code> if you don't have them:</p>

<pre><code class="r">install.packages(c("ggplot2","gridExtra"), repos = "http://cran.rstudio.com")
</code></pre>

<p>And their use:</p>

<p><strong>Logistic histogram plots</strong></p>

<pre><code class="r">loghistplot(data=mtcars[,c("mpg","vs")])
</code></pre>

<p><img src="/public/img/2014-05-22-logplotreboot/unnamed-chunk-5.png" alt="plot of chunk unnamed-chunk-5" /></p>

<pre><code class="r">loghistplot(movies[,c("rating","Action")])
</code></pre>

<p><img src="/public/img/2014-05-22-logplotreboot/unnamed-chunk-6.png" alt="plot of chunk unnamed-chunk-6" /></p>

<p><strong>Logistic point plots</strong></p>

<pre><code class="r">loghistplot(data=mtcars[,c("mpg","vs")])
</code></pre>

<p><img src="/public/img/2014-05-22-logplotreboot/unnamed-chunk-7.png" alt="plot of chunk unnamed-chunk-7" /></p>

<pre><code class="r">loghistplot(movies[,c("rating","Action")])
</code></pre>

<p><img src="/public/img/2014-05-22-logplotreboot/unnamed-chunk-8.png" alt="plot of chunk unnamed-chunk-8" /></p>

  </div>
  
</div>

<!-- Pagination links -->
<div class="pagination">
  
    <a href="/page5" class="older">Older</a>
  
  
    
      <a href="/page3" class="newer">Newer</a>
    
  
</div>

    </div>

  </body>

  <footer>  
  <!-- Disqus code -->
  <script type="text/javascript">
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = 'recology'; // required: replace example with your forum shortname

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function () {
          var s = document.createElement('script'); s.async = true;
          s.type = 'text/javascript';
          s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
          (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
      }());
  </script>

  <!-- Gaug.es Analytics -->
  <script type="text/javascript">
    var _gauges = _gauges || [];
    (function() {
      var t   = document.createElement('script');
      t.type  = 'text/javascript';
      t.async = true;
      t.id    = 'gauges-tracker';
      t.setAttribute('data-site-id', '4efd83a6f5a1f5158a000004');
      t.src = '//secure.gaug.es/track.js';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(t, s);
    })();
  </script>
</footer>
</html>
