---
name: code
layout: post
title: On writing, sharing, collaborating, and hosting code for science
date: 2013-07-20
author: Scott Chamberlain
tags:
- R
- code
- github
---

I recently engaged with a number of tweeps on the topic of where to host code. I started it off by saying  

> Rule number 1 wrt science code: DO NOT post your code on your personal website

I think it was difficult to convey my position on the matter. So here goes. 

### Code writing during analyses, etc.

When you write code for a paper to do simulations, anlayses, data manipulation, visualization - whatever it is - it will help to version your code. That is, not naming files like *myfile_v1.r*, *myfile_v2.r*, etc., but with versioning using version control systems (VCS) like [git][git], [svn][svn], [mercurial][mc], etc. Although git will give you headaches during the learning process, it takes care of versioning your code for you, finding differences in different versions, helps you manage conflicts from different contributors, and allows you to restore that old code you accidentally deleted. 

And you don't have to use git or svn on a code hosting site - you can use git or svn locally on your own machine. However, there are many benefits to putting your code up on the interwebs. 

Do have a look at [Karthik Ram's][kr] paper on how git can facilitate greater reproducibility and transparency in science [here][karthik].

### Collaborating on code

Whenever you collaborate on code writing you have the extreme joy of dealing with conflicts. Perhaps you use Dropbox for collaborating on some code writing. Crap, now there is a line of code that messes up the analysis, and you don't know who put it there, and why it's there. If you only knew who to ask? Wouldn't it be nice to have a place to collect bugs in the code. 

All of these things become easy if you host code on a service such as Github. If you are already versioning your code with git you are in luck - all you need to do is create an account on github/bitbucket and push your code up. If not, you should definitley learn git.

Hosting your code on Github (or Bitbucket, etc.) allows each collaborator to work separately on the code simultaneously, then merge their code together, while git helps you take manage of the merge. An awesome feature of git (and other VCS's) is branching. What the heck is that? Basically, you can create a complete copy of your git project, do any changes you want, then throw it away or merge it back in to your main branch. Pretty sweet. 

### Sharing your code

XXXX

### Contributing to the software you use

Much of the software you and I use in R, Python, etc. is likely hosted on a code hosting platform such as Github, Bitbucket, R-Forge, etc. Code gets better faster if its users report bugs to the software authors. By creating an account on Github, for example, you can easily report bugs or request features where the software is developed. This is better than email as only those two people get the benefit of learning from the conversation. Some software projects have mailing lists, which is another great way to contribute/ask questions. 

[git]: http://git-scm.com/
[svn]: http://subversion.apache.org/
[karthik]: http://www.scfbm.org/content/8/1/7/abstract
[kr]: http://inundata.org/
[mc]: http://mercurial.selenic.com/wiki/