---
name: http-codes
layout: post
title: http codes
date: 2014-12-02T16:01:50Z
author: Scott Chamberlain
tags:
- R
- API
- http
---

```{r, echo=FALSE}
knitr::opts_chunk$set(
  collapse=TRUE,
  comment="#>",
  warning=FALSE,
  message=FALSE
)
```

Recently noticed a little Python library called [httpcode](https://github.com/rspivak/httpcode) that does a simple thing: gives information on http codes in the CLI. I thought this could maybe potentially be useful for R. So I made an R version. 

## Installation

```{r eval=FALSE}
devtools::install_github("sckott/httpcode")
```

```{r}
library("httpcode")
```

## Search by http code

```{r}
http_code(100)
```

```{r}
http_code(400)
```

```{r}
http_code(503)
```

```{r}
http_code(999)
```

## Fuzzy code search

```{r}
http_code('1xx')
```

```{r}
http_code('3xx')
```

```{r}
http_code('30[12]')
```

```{r}
http_code('30[34]')
```

## Search by text message

```{r}
http_search("request")
```

```{r}
http_search("forbidden")
```

```{r}
http_search("too")
```

```{r}
http_search("birds")
```
